---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-networking-laboys-org-v1alpha1-externalproxy
  failurePolicy: Fail
  name: mexternalproxy-v1alpha1.kb.io
  rules:
  - apiGroups:
    - networking.laboys.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - externalproxies
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-networking-laboys-org-v1alpha1-externalproxy
  failurePolicy: Fail
  name: vexternalproxy-v1alpha1.kb.io
  rules:
  - apiGroups:
    - networking.laboys.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - externalproxies
  sideEffects: None
