kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.rbac.name }}-edit
  labels:
    {{- include "mobius-manager.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - networking.laboys.org
    resources:
      - externalproxies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - networking.laboys.org
    resources:
      - externalproxies/status
    verbs:
      - get
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.rbac.name }}-view
  labels:
    {{- include "mobius-manager.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - networking.laboys.org
    resources:
      - externalproxies
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.laboys.org
    resources:
      - externalproxies/status
    verbs:
      - get
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.rbac.name }}-controller
  labels:
    {{- include "mobius-manager.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - networking.laboys.org
    resources:
      - externalproxies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - networking.laboys.org
    resources:
      - externalproxies/finalizers
    verbs:
      - update
  - apiGroups:
      - networking.laboys.org
    resources:
      - externalproxies/status
    verbs:
      - get
      - patch
      - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.rbac.name }}-controller
  labels:
    {{- include "mobius-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: {{ .Values.rbac.name }}-controller
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "mobius-manager.fullname" . }}
    namespace: {{ .Release.Namespace }}
