# permissions for end users to edit externalproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: mobius
    app.kubernetes.io/managed-by: kustomize
  name: networking-externalproxy-editor-role
rules:
- apiGroups:
  - networking.laboys.org
  resources:
  - externalproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.laboys.org
  resources:
  - externalproxies/status
  verbs:
  - get
